name: Demo SpringBoot CI/CD

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"
          cache: maven

      - name: Verify Java version
        run: java -version

      - name: Build with Maven
        run: mvn clean package -DskipTests --batch-mode
