name: Demo SpringBoot CI/CD

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Set up Java 21 (Temurin = Eclipse Adoptium)
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"
          cache: maven

      # 3️⃣ Print Java version để xác nhận đúng 21
      - name: Verify Java version
        run: java -version

      # 4️⃣ Build project (vì code nằm trong thư mục demo/)
      - name: Build with Maven
        run: mvn -f demo/pom.xml clean package --batch-mode -DskipTests
