name: Demo SpringBoot CI/CD

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️ Lấy code từ repository
      - uses: actions/checkout@v2

      # 2️ Cài đặt JDK (ở đây dùng Java 17, nếu bạn thích giữ 11 cũng được)
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: "17"
          distribution: "temurin"

      # 3️ Build với Maven (vì project của bạn nằm trong thư mục demo/)
      - name: Build with Maven
        run: mvn -f demo/pom.xml --batch-mode --update-snapshots verify
