name: CI - Build & Test Spring Boot with Maven

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️ Lấy code từ repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️ Cài đặt JDK 17 (hoặc phiên bản bạn dùng)
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven

      # 3️ Build project bằng Maven
      - name: Build with Maven
        run: mvn -f demo/pom.xml clean package -DskipTests

      # 4️ Chạy test (nếu có)
      - name: Run tests
        run: mvn -f demo/pom.xml test

      # 5️ (Tuỳ chọn) Upload kết quả build để xem trong GitHub
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: spring-boot-jar
          path: demo/target/*.jar
